export type BotOrNotAnswer = "bot" | "human";

export type BotOrNotScenario = {
  id: string;
  title: string;
  difficulty: "easy" | "medium" | "hard";
  facts: { label: string; value: string }[];
  answer: BotOrNotAnswer;
  explanation: string;
};

export const BOT_OR_NOT_CONFIG = {
  rounds: 5,
  timeLimitSeconds: 20,
  pointsPerCorrect: 20,
};

export const BOT_OR_NOT_SCENARIOS: BotOrNotScenario[] = [
  {
    id: "bot-001",
    title: "Login Storm",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "POST /login" },
      { label: "Requests", value: "8,400 / minute" },
      { label: "Same IP", value: "YES" },
      { label: "Different usernames", value: "YES" },
      { label: "Human-like browsing", value: "NO" },
    ],
    answer: "bot",
    explanation: "One IP trying thousands of usernames on login is credential stuffing.",
  },
  {
    id: "bot-002",
    title: "Sunday Shopper",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "GET /products" },
      { label: "Requests", value: "14 in 8 minutes" },
      { label: "Mouse movement", value: "YES" },
      { label: "Pages viewed", value: "Home → Sale → Cart" },
      { label: "Same session", value: "YES" },
    ],
    answer: "human",
    explanation: "Slow browsing with a natural path through the shop looks like a person.",
  },
  {
    id: "bot-003",
    title: "Copy Machine",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "GET /prices.json" },
      { label: "Requests", value: "Every 0.2 seconds" },
      { label: "User-Agent", value: "python-requests/2.31" },
      { label: "JavaScript", value: "NOT EXECUTED" },
      { label: "Cookies", value: "NONE" },
    ],
    answer: "bot",
    explanation: "A scripted client hitting a data URL on a metronome is a scraper.",
  },
  {
    id: "bot-004",
    title: "Forgot Password",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "POST /login" },
      { label: "Attempts", value: "3 in 2 minutes" },
      { label: "Same username", value: "YES" },
      { label: "Typos in password", value: "YES" },
      { label: "Then", value: "Clicked Reset password" },
    ],
    answer: "human",
    explanation: "A few failed tries on one account, then a reset, is a person who forgot.",
  },
  {
    id: "bot-005",
    title: "Ticket Rush",
    difficulty: "medium",
    facts: [
      { label: "Endpoint", value: "POST /checkout" },
      { label: "Requests", value: "900 carts in 12 seconds" },
      { label: "Inventory", value: "Only concert tickets" },
      { label: "Payment methods", value: "Rotating cards" },
      { label: "Device IDs", value: "Almost identical" },
    ],
    answer: "bot",
    explanation: "Mass checkout of one hot item with cloned devices is a scalp bot.",
  },
  {
    id: "bot-006",
    title: "Coffee Break Cart",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "POST /cart" },
      { label: "Adds", value: "2 items" },
      { label: "Idle time", value: "11 minutes" },
      { label: "Then", value: "Completed checkout" },
      { label: "Typing speed", value: "Normal" },
    ],
    answer: "human",
    explanation: "A pause in the middle of checkout is typical for a person, not a script.",
  },
  {
    id: "bot-007",
    title: "Header Farm",
    difficulty: "medium",
    facts: [
      { label: "Endpoint", value: "GET /search" },
      { label: "Requests", value: "2,200 / minute" },
      { label: "User-Agent", value: "Swaps every request" },
      { label: "TLS fingerprint", value: "Always the same" },
      { label: "Query terms", value: "Sequential SKUs" },
    ],
    answer: "bot",
    explanation: "Fake browsers on top of one TLS fingerprint and sequential SKUs is automation.",
  },
  {
    id: "bot-008",
    title: "Support Chat",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "POST /chat" },
      { label: "Messages", value: "4" },
      { label: "Typos", value: "YES" },
      { label: "Waited for reply", value: "YES" },
      { label: "Time of day", value: "Local afternoon" },
    ],
    answer: "human",
    explanation: "Slow, messy chat with waiting in between is a person asking for help.",
  },
  {
    id: "bot-009",
    title: "Gift Card Guessing",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "POST /giftcard/redeem" },
      { label: "Requests", value: "5,000 codes" },
      { label: "Success rate", value: "0.04%" },
      { label: "Same IP range", value: "YES" },
      { label: "Interval", value: "Exactly 50ms" },
    ],
    answer: "bot",
    explanation: "Trying thousands of codes on a clock is carding, not a shopper.",
  },
  {
    id: "bot-010",
    title: "New Phone",
    difficulty: "medium",
    facts: [
      { label: "Endpoint", value: "POST /signup" },
      { label: "Device", value: "Brand-new phone model" },
      { label: "Form fill", value: "24 seconds" },
      { label: "Autofill", value: "YES" },
      { label: "Followed by", value: "Opened settings" },
    ],
    answer: "human",
    explanation: "One signup with autofill and then poking around settings is a real new user.",
  },
  {
    id: "bot-011",
    title: "Headless Horde",
    difficulty: "medium",
    facts: [
      { label: "Endpoint", value: "GET /home" },
      { label: "WebGL", value: "MISSING" },
      { label: "Screen size", value: "0×0" },
      { label: "Plugins", value: "NONE" },
      { label: "Requests", value: "400 hosts, same second" },
    ],
    answer: "bot",
    explanation: "No graphics, no screen, many hosts at once — headless browsers.",
  },
  {
    id: "bot-012",
    title: "Grandparent Gift",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "GET /help" },
      { label: "Clicks", value: "Back button 6 times" },
      { label: "Zoom", value: "150%" },
      { label: "Session length", value: "18 minutes" },
      { label: "Checkout", value: "One sweater" },
    ],
    answer: "human",
    explanation: "Zoomed-in, lots of back clicks, one small order is a person finding their way.",
  },
  {
    id: "bot-013",
    title: "API Hammer",
    difficulty: "medium",
    facts: [
      { label: "Endpoint", value: "GET /api/v1/users" },
      { label: "Auth", value: "Stolen token" },
      { label: "Pagination", value: "page=1 through page=9000" },
      { label: "Rate", value: "Maxed every limit" },
      { label: "UI pages", value: "NEVER OPENED" },
    ],
    answer: "bot",
    explanation: "Walking an API page by page with a stolen token is automated harvesting.",
  },
  {
    id: "bot-014",
    title: "Train Wi-Fi",
    difficulty: "hard",
    facts: [
      { label: "Endpoint", value: "GET /feed" },
      { label: "IP", value: "Shared public Wi-Fi" },
      { label: "Many devices", value: "YES" },
      { label: "Behavior", value: "Each device unique" },
      { label: "Scroll patterns", value: "Irregular" },
    ],
    answer: "human",
    explanation: "Lots of people on one IP can look noisy, but unique devices and messy scrolling are humans.",
  },
  {
    id: "bot-015",
    title: "Coupon Rain",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "POST /coupon" },
      { label: "Codes tried", value: "SAVE10, SAVE11, SAVE12…" },
      { label: "Speed", value: "80 codes / second" },
      { label: "Cart", value: "Empty" },
      { label: "Account age", value: "Created 20 seconds ago" },
    ],
    answer: "bot",
    explanation: "Sequential coupon guessing from a brand-new account is automation.",
  },
  {
    id: "bot-016",
    title: "Recipe Rabbit Hole",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "GET /articles" },
      { label: "Pages", value: "7 related posts" },
      { label: "Time on page", value: "40–90 seconds" },
      { label: "Comments", value: "Left one" },
      { label: "Ad clicks", value: "Accidentally 1" },
    ],
    answer: "human",
    explanation: "Reading, commenting, and a stray ad click is a person wandering a site.",
  },
  {
    id: "bot-017",
    title: "Fake Reviews",
    difficulty: "medium",
    facts: [
      { label: "Endpoint", value: "POST /review" },
      { label: "Reviews", value: "120 five-stars in 10 minutes" },
      { label: "Text", value: "Nearly identical" },
      { label: "Accounts", value: "Created today" },
      { label: "Purchases", value: "NONE" },
    ],
    answer: "bot",
    explanation: "A burst of identical 5-star reviews from new accounts with no purchases is fake.",
  },
  {
    id: "bot-018",
    title: "Office NAT",
    difficulty: "hard",
    facts: [
      { label: "Endpoint", value: "GET /dashboard" },
      { label: "IP", value: "One company gateway" },
      { label: "Employees", value: "80 logged in" },
      { label: "Work hours", value: "YES" },
      { label: "Keystroke timing", value: "Human variance" },
    ],
    answer: "human",
    explanation: "Many users behind one office IP during work hours still look like people.",
  },
  {
    id: "bot-019",
    title: "Inventory Probe",
    difficulty: "medium",
    facts: [
      { label: "Endpoint", value: "HEAD /sku/{id}" },
      { label: "IDs", value: "000000 to 400000" },
      { label: "Errors ignored", value: "YES" },
      { label: "Referrer", value: "NONE" },
      { label: "Accept-Language", value: "MISSING" },
    ],
    answer: "bot",
    explanation: "Walking every SKU ID with HEAD requests and no browser headers is a probe.",
  },
  {
    id: "bot-020",
    title: "Late Night Gamer",
    difficulty: "easy",
    facts: [
      { label: "Endpoint", value: "POST /api/match" },
      { label: "Time", value: "1:14 AM local" },
      { label: "Retries after lag", value: "YES" },
      { label: "Chat", value: "gg" },
      { label: "Session", value: "47 minutes" },
    ],
    answer: "human",
    explanation: "A long session, lag retries, and a short chat message is a person playing.",
  },
];
